api:
  key: 931B8F2712DB4C91BF256DE0E510FCD0
plugins:
  announcements:
    _config_version: 1
  discovery:
    upnpUuid: ab414af7-4f7e-4d58-8b81-973726bb4612
  errortracking:
    unique_id: 4dd5ed44-6c1a-4c78-9e0f-559939bd6ec5
  gcodeviewer:
    _config_version: 1
  softwareupdate:
    _config_version: 9
  tracking:
    unique_id: 082fca84-20dc-4630-adb0-22022ac547b5
  virtual_printer:
    _config_version: 1
printerProfiles:
  default: _default
server:
  secretKey: PCFpbQ5GRXLLkw8J6Hv3VQrxQDa1paE7
