# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from print_nanny_client.api_client import ApiClient


class GcodeFilesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def gcode_files_create(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_create(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
            return data

    def gcode_files_create_with_http_info(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name2' is set
        if ('name2' not in params or
                params['name2'] is None):
            raise ValueError("Missing the required parameter `name2` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file2' is set
        if ('file2' not in params or
                params['file2'] is None):
            raise ValueError("Missing the required parameter `file2` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file_hash2' is set
        if ('file_hash2' not in params or
                params['file_hash2'] is None):
            raise ValueError("Missing the required parameter `file_hash2` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file' is set
        if ('file' not in params or
                params['file'] is None):
            raise ValueError("Missing the required parameter `file` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file_hash' is set
        if ('file_hash' not in params or
                params['file_hash'] is None):
            raise ValueError("Missing the required parameter `file_hash` when calling `gcode_files_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_create(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_create(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
            return data

    def gcode_files_create_with_http_info(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name2' is set
        if ('name2' not in params or
                params['name2'] is None):
            raise ValueError("Missing the required parameter `name2` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file2' is set
        if ('file2' not in params or
                params['file2'] is None):
            raise ValueError("Missing the required parameter `file2` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file_hash2' is set
        if ('file_hash2' not in params or
                params['file_hash2'] is None):
            raise ValueError("Missing the required parameter `file_hash2` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file' is set
        if ('file' not in params or
                params['file'] is None):
            raise ValueError("Missing the required parameter `file` when calling `gcode_files_create`")  # noqa: E501
        # verify the required parameter 'file_hash' is set
        if ('file_hash' not in params or
                params['file_hash'] is None):
            raise ValueError("Missing the required parameter `file_hash` when calling `gcode_files_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_list(self, **kwargs):  # noqa: E501
        """gcode_files_list  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :return: PaginatedGcodeFileList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def gcode_files_list_with_http_info(self, **kwargs):  # noqa: E501
        """gcode_files_list  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :return: PaginatedGcodeFileList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['limit', 'offset']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedGcodeFileList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_partial_update(self, id, **kwargs):  # noqa: E501
        """gcode_files_partial_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_partial_update(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: A unique integer value identifying this gcode file. (required)
        :param str name2:
        :param str file2:
        :param str file_hash2:
        :param str name:
        :param str file:
        :param str file_hash:
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_partial_update_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_partial_update_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def gcode_files_partial_update_with_http_info(self, id, **kwargs):  # noqa: E501
        """gcode_files_partial_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_partial_update_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: A unique integer value identifying this gcode file. (required)
        :param str name2:
        :param str file2:
        :param str file_hash2:
        :param str name:
        :param str file:
        :param str file_hash:
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `gcode_files_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_partial_update(self, id, **kwargs):  # noqa: E501
        """gcode_files_partial_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_partial_update(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: A unique integer value identifying this gcode file. (required)
        :param str name2:
        :param str file2:
        :param str file_hash2:
        :param str name:
        :param str file:
        :param str file_hash:
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_partial_update_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_partial_update_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def gcode_files_partial_update_with_http_info(self, id, **kwargs):  # noqa: E501
        """gcode_files_partial_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_partial_update_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: A unique integer value identifying this gcode file. (required)
        :param str name2:
        :param str file2:
        :param str file_hash2:
        :param str name:
        :param str file:
        :param str file_hash:
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `gcode_files_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_retrieve(self, id, **kwargs):  # noqa: E501
        """gcode_files_retrieve  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_retrieve(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: A unique integer value identifying this gcode file. (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_retrieve_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_retrieve_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def gcode_files_retrieve_with_http_info(self, id, **kwargs):  # noqa: E501
        """gcode_files_retrieve  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_retrieve_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: A unique integer value identifying this gcode file. (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_retrieve" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `gcode_files_retrieve`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/{id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_update(self, name2, file2, file_hash2, name, file, file_hash, id, **kwargs):  # noqa: E501
        """gcode_files_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update(name2, file2, file_hash2, name, file, file_hash, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :param int id: A unique integer value identifying this gcode file. (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_update_with_http_info(name2, file2, file_hash2, name, file, file_hash, id, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_update_with_http_info(name2, file2, file_hash2, name, file, file_hash, id, **kwargs)  # noqa: E501
            return data

    def gcode_files_update_with_http_info(self, name2, file2, file_hash2, name, file, file_hash, id, **kwargs):  # noqa: E501
        """gcode_files_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update_with_http_info(name2, file2, file_hash2, name, file, file_hash, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :param int id: A unique integer value identifying this gcode file. (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name2' is set
        if ('name2' not in params or
                params['name2'] is None):
            raise ValueError("Missing the required parameter `name2` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file2' is set
        if ('file2' not in params or
                params['file2'] is None):
            raise ValueError("Missing the required parameter `file2` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file_hash2' is set
        if ('file_hash2' not in params or
                params['file_hash2'] is None):
            raise ValueError("Missing the required parameter `file_hash2` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file' is set
        if ('file' not in params or
                params['file'] is None):
            raise ValueError("Missing the required parameter `file` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file_hash' is set
        if ('file_hash' not in params or
                params['file_hash'] is None):
            raise ValueError("Missing the required parameter `file_hash` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `gcode_files_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_update(self, name2, file2, file_hash2, name, file, file_hash, id, **kwargs):  # noqa: E501
        """gcode_files_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update(name2, file2, file_hash2, name, file, file_hash, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :param int id: A unique integer value identifying this gcode file. (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_update_with_http_info(name2, file2, file_hash2, name, file, file_hash, id, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_update_with_http_info(name2, file2, file_hash2, name, file, file_hash, id, **kwargs)  # noqa: E501
            return data

    def gcode_files_update_with_http_info(self, name2, file2, file_hash2, name, file, file_hash, id, **kwargs):  # noqa: E501
        """gcode_files_update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update_with_http_info(name2, file2, file_hash2, name, file, file_hash, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :param int id: A unique integer value identifying this gcode file. (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name2' is set
        if ('name2' not in params or
                params['name2'] is None):
            raise ValueError("Missing the required parameter `name2` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file2' is set
        if ('file2' not in params or
                params['file2'] is None):
            raise ValueError("Missing the required parameter `file2` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file_hash2' is set
        if ('file_hash2' not in params or
                params['file_hash2'] is None):
            raise ValueError("Missing the required parameter `file_hash2` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file' is set
        if ('file' not in params or
                params['file'] is None):
            raise ValueError("Missing the required parameter `file` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'file_hash' is set
        if ('file_hash' not in params or
                params['file_hash'] is None):
            raise ValueError("Missing the required parameter `file_hash` when calling `gcode_files_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `gcode_files_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_update_or_create(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_update_or_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update_or_create(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_update_or_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_update_or_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
            return data

    def gcode_files_update_or_create_with_http_info(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_update_or_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update_or_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_update_or_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name2' is set
        if ('name2' not in params or
                params['name2'] is None):
            raise ValueError("Missing the required parameter `name2` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file2' is set
        if ('file2' not in params or
                params['file2'] is None):
            raise ValueError("Missing the required parameter `file2` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file_hash2' is set
        if ('file_hash2' not in params or
                params['file_hash2'] is None):
            raise ValueError("Missing the required parameter `file_hash2` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file' is set
        if ('file' not in params or
                params['file'] is None):
            raise ValueError("Missing the required parameter `file` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file_hash' is set
        if ('file_hash' not in params or
                params['file_hash'] is None):
            raise ValueError("Missing the required parameter `file_hash` when calling `gcode_files_update_or_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/update_or_create/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gcode_files_update_or_create(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_update_or_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update_or_create(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gcode_files_update_or_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
        else:
            (data) = self.gcode_files_update_or_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, **kwargs)  # noqa: E501
            return data

    def gcode_files_update_or_create_with_http_info(self, name2, file2, file_hash2, name, file, file_hash, **kwargs):  # noqa: E501
        """gcode_files_update_or_create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gcode_files_update_or_create_with_http_info(name2, file2, file_hash2, name, file, file_hash, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name2: (required)
        :param str file2: (required)
        :param str file_hash2: (required)
        :param str name: (required)
        :param str file: (required)
        :param str file_hash: (required)
        :return: GcodeFile
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name2', 'file2', 'file_hash2', 'name', 'file', 'file_hash']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gcode_files_update_or_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name2' is set
        if ('name2' not in params or
                params['name2'] is None):
            raise ValueError("Missing the required parameter `name2` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file2' is set
        if ('file2' not in params or
                params['file2'] is None):
            raise ValueError("Missing the required parameter `file2` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file_hash2' is set
        if ('file_hash2' not in params or
                params['file_hash2'] is None):
            raise ValueError("Missing the required parameter `file_hash2` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file' is set
        if ('file' not in params or
                params['file'] is None):
            raise ValueError("Missing the required parameter `file` when calling `gcode_files_update_or_create`")  # noqa: E501
        # verify the required parameter 'file_hash' is set
        if ('file_hash' not in params or
                params['file_hash'] is None):
            raise ValueError("Missing the required parameter `file_hash` when calling `gcode_files_update_or_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'file_hash' in params:
            form_params.append(('file_hash', params['file_hash']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['cookieAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/gcode_files/update_or_create/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GcodeFile',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
