# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import print_nanny_client
from print_nanny_client.api.print_jobs_api import PrintJobsApi  # noqa: E501


class TestPrintJobsApi(unittest.TestCase):
    """PrintJobsApi unit test stubs"""

    def setUp(self):
        self.api = PrintJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_print_jobs_create(self):
        """Test case for print_jobs_create

        """
        pass

    def test_print_jobs_list(self):
        """Test case for print_jobs_list

        """
        pass

    def test_print_jobs_partial_update(self):
        """Test case for print_jobs_partial_update

        """
        pass

    def test_print_jobs_retrieve(self):
        """Test case for print_jobs_retrieve

        """
        pass

    def test_print_jobs_update(self):
        """Test case for print_jobs_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
