# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import print_nanny_client
from print_nanny_client.api.predict_events_api import PredictEventsApi  # noqa: E501


class TestPredictEventsApi(unittest.TestCase):
    """PredictEventsApi unit test stubs"""

    def setUp(self):
        self.api = PredictEventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_predict_events_create(self):
        """Test case for predict_events_create

        """
        pass

    def test_predict_events_list(self):
        """Test case for predict_events_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
