# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import print_nanny_client
from print_nanny_client.models.paginated_print_job_list import PaginatedPrintJobList  # noqa: E501
from print_nanny_client.rest import ApiException


class TestPaginatedPrintJobList(unittest.TestCase):
    """PaginatedPrintJobList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedPrintJobList(self):
        """Test PaginatedPrintJobList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = print_nanny_client.models.paginated_print_job_list.PaginatedPrintJobList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
