# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import print_nanny_client
from print_nanny_client.model.user_request import UserRequest


class TestUserRequest(unittest.TestCase):
    """UserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserRequest(self):
        """Test UserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
