# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import print_nanny_client
from print_nanny_client.api.gcode_files_api import GcodeFilesApi  # noqa: E501
from print_nanny_client.rest import ApiException


class TestGcodeFilesApi(unittest.TestCase):
    """GcodeFilesApi unit test stubs"""

    def setUp(self):
        self.api = print_nanny_client.api.gcode_files_api.GcodeFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gcode_files_create(self):
        """Test case for gcode_files_create

        """
        pass

    def test_gcode_files_list(self):
        """Test case for gcode_files_list

        """
        pass

    def test_gcode_files_partial_update(self):
        """Test case for gcode_files_partial_update

        """
        pass

    def test_gcode_files_retrieve(self):
        """Test case for gcode_files_retrieve

        """
        pass

    def test_gcode_files_update(self):
        """Test case for gcode_files_update

        """
        pass

    def test_gcode_files_update_or_create(self):
        """Test case for gcode_files_update_or_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
