# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import print_nanny_client
from print_nanny_client.models.patched_gcode_file_request import PatchedGcodeFileRequest  # noqa: E501
from print_nanny_client.rest import ApiException


class TestPatchedGcodeFileRequest(unittest.TestCase):
    """PatchedGcodeFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedGcodeFileRequest(self):
        """Test PatchedGcodeFileRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = print_nanny_client.models.patched_gcode_file_request.PatchedGcodeFileRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
