# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import print_nanny_client
from print_nanny_client.model.patched_print_job_request import PatchedPrintJobRequest


class TestPatchedPrintJobRequest(unittest.TestCase):
    """PatchedPrintJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedPrintJobRequest(self):
        """Test PatchedPrintJobRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedPrintJobRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
