# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.printer_profiles_api import PrinterProfilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPrinterProfilesApi(unittest.TestCase):
    """PrinterProfilesApi unit test stubs"""

    def setUp(self):
        self.api = PrinterProfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_printer_profiles_create(self):
        """Test case for printer_profiles_create

        """
        pass

    def test_printer_profiles_list(self):
        """Test case for printer_profiles_list

        """
        pass

    def test_printer_profiles_partial_update(self):
        """Test case for printer_profiles_partial_update

        """
        pass

    def test_printer_profiles_retrieve(self):
        """Test case for printer_profiles_retrieve

        """
        pass

    def test_printer_profiles_update(self):
        """Test case for printer_profiles_update

        """
        pass

    def test_printer_profiles_update_or_create(self):
        """Test case for printer_profiles_update_or_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
