# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.printer_profile import PrinterProfile  # noqa: E501
from swagger_client.rest import ApiException


class TestPrinterProfile(unittest.TestCase):
    """PrinterProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrinterProfile(self):
        """Test PrinterProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.printer_profile.PrinterProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
