# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.schema_api import SchemaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self):
        self.api = SchemaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_schema_retrieve(self):
        """Test case for schema_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
