# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from print_nanny_client.configuration import Configuration


class PredictEventRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dt': 'datetime',
        'event_data': 'dict(str, object)',
        'predict_data': 'dict(str, object)',
        'files': 'int',
        'print_job': 'int',
        'plugin_version': 'str',
        'octoprint_version': 'str'
    }

    attribute_map = {
        'dt': 'dt',
        'event_data': 'event_data',
        'predict_data': 'predict_data',
        'files': 'files',
        'print_job': 'print_job',
        'plugin_version': 'plugin_version',
        'octoprint_version': 'octoprint_version'
    }

    def __init__(self, dt=None, event_data=None, predict_data=None, files=None, print_job=None, plugin_version=None, octoprint_version=None, local_vars_configuration=None):  # noqa: E501
        """PredictEventRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dt = None
        self._event_data = None
        self._predict_data = None
        self._files = None
        self._print_job = None
        self._plugin_version = None
        self._octoprint_version = None
        self.discriminator = None

        if dt is not None:
            self.dt = dt
        self.event_data = event_data
        self.predict_data = predict_data
        self.files = files
        self.print_job = print_job
        self.plugin_version = plugin_version
        self.octoprint_version = octoprint_version

    @property
    def dt(self):
        """Gets the dt of this PredictEventRequest.  # noqa: E501


        :return: The dt of this PredictEventRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._dt

    @dt.setter
    def dt(self, dt):
        """Sets the dt of this PredictEventRequest.


        :param dt: The dt of this PredictEventRequest.  # noqa: E501
        :type dt: datetime
        """

        self._dt = dt

    @property
    def event_data(self):
        """Gets the event_data of this PredictEventRequest.  # noqa: E501


        :return: The event_data of this PredictEventRequest.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._event_data

    @event_data.setter
    def event_data(self, event_data):
        """Sets the event_data of this PredictEventRequest.


        :param event_data: The event_data of this PredictEventRequest.  # noqa: E501
        :type event_data: dict(str, object)
        """

        self._event_data = event_data

    @property
    def predict_data(self):
        """Gets the predict_data of this PredictEventRequest.  # noqa: E501


        :return: The predict_data of this PredictEventRequest.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._predict_data

    @predict_data.setter
    def predict_data(self, predict_data):
        """Sets the predict_data of this PredictEventRequest.


        :param predict_data: The predict_data of this PredictEventRequest.  # noqa: E501
        :type predict_data: dict(str, object)
        """
        if self.local_vars_configuration.client_side_validation and predict_data is None:  # noqa: E501
            raise ValueError("Invalid value for `predict_data`, must not be `None`")  # noqa: E501

        self._predict_data = predict_data

    @property
    def files(self):
        """Gets the files of this PredictEventRequest.  # noqa: E501


        :return: The files of this PredictEventRequest.  # noqa: E501
        :rtype: int
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this PredictEventRequest.


        :param files: The files of this PredictEventRequest.  # noqa: E501
        :type files: int
        """
        if self.local_vars_configuration.client_side_validation and files is None:  # noqa: E501
            raise ValueError("Invalid value for `files`, must not be `None`")  # noqa: E501

        self._files = files

    @property
    def print_job(self):
        """Gets the print_job of this PredictEventRequest.  # noqa: E501


        :return: The print_job of this PredictEventRequest.  # noqa: E501
        :rtype: int
        """
        return self._print_job

    @print_job.setter
    def print_job(self, print_job):
        """Sets the print_job of this PredictEventRequest.


        :param print_job: The print_job of this PredictEventRequest.  # noqa: E501
        :type print_job: int
        """
        if self.local_vars_configuration.client_side_validation and print_job is None:  # noqa: E501
            raise ValueError("Invalid value for `print_job`, must not be `None`")  # noqa: E501

        self._print_job = print_job

    @property
    def plugin_version(self):
        """Gets the plugin_version of this PredictEventRequest.  # noqa: E501


        :return: The plugin_version of this PredictEventRequest.  # noqa: E501
        :rtype: str
        """
        return self._plugin_version

    @plugin_version.setter
    def plugin_version(self, plugin_version):
        """Sets the plugin_version of this PredictEventRequest.


        :param plugin_version: The plugin_version of this PredictEventRequest.  # noqa: E501
        :type plugin_version: str
        """
        if self.local_vars_configuration.client_side_validation and plugin_version is None:  # noqa: E501
            raise ValueError("Invalid value for `plugin_version`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                plugin_version is not None and len(plugin_version) > 30):
            raise ValueError("Invalid value for `plugin_version`, length must be less than or equal to `30`")  # noqa: E501

        self._plugin_version = plugin_version

    @property
    def octoprint_version(self):
        """Gets the octoprint_version of this PredictEventRequest.  # noqa: E501


        :return: The octoprint_version of this PredictEventRequest.  # noqa: E501
        :rtype: str
        """
        return self._octoprint_version

    @octoprint_version.setter
    def octoprint_version(self, octoprint_version):
        """Sets the octoprint_version of this PredictEventRequest.


        :param octoprint_version: The octoprint_version of this PredictEventRequest.  # noqa: E501
        :type octoprint_version: str
        """
        if self.local_vars_configuration.client_side_validation and octoprint_version is None:  # noqa: E501
            raise ValueError("Invalid value for `octoprint_version`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                octoprint_version is not None and len(octoprint_version) > 30):
            raise ValueError("Invalid value for `octoprint_version`, length must be less than or equal to `30`")  # noqa: E501

        self._octoprint_version = octoprint_version

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PredictEventRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PredictEventRequest):
            return True

        return self.to_dict() != other.to_dict()
